### ISSUE TITLE
Launcher goes into loop

### ISSUE THREAD

**Issue by jwulf** [salboaie/SwarmCore#7]
This is on Ubuntu 15.04:

Watching  /root/workspace/SwarmCore/etc/adapters/AtmaCalendarAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMindBodyAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNotificationAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNewCustomerConciergeAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaCalendarAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMindBodyAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNotificationAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNewCustomerConciergeAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaCalendarAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMindBodyAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNotificationAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNewCustomerConciergeAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaCalendarAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMindBodyAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNotificationAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNewCustomerConciergeAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaCalendarAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMindBodyAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNotificationAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNewCustomerConciergeAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaCalendarAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMailAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaMindBodyAdapter.js
Watching  /root/workspace/SwarmCore/etc/adapters/AtmaNotificationAdapter.js

looping over and over again, with no mercy. 

The exact same code runs fine on my Mac. Both are using node v0.12.4.

**Comment by jwulf** [comment]
Tried it on a Ubuntu 14.10 x86_64 image - same deal.

Reimaged with Ubuntu 15.04 32-bit,runs stably. 

Seems to be on x86_64 arch.

**Comment by salboaie** [comment]
Interesting. I use centos 7, 64 bit without issues.
I assume that the adapter is running fine alone and it is not crushing.
Could you go and debug a bit launcher code to see why it thinks that the
forked project is dead and goes to a restart?

I could try to build a docker image with Ubuntu, hopefully got some time
tomorrow.

**Comment by jwulf** [comment]
Looks like:

https://github.com/salboaie/SwarmCore/blob/master/com/launcher/executionMonitor.js#L64

Should be:

this.alive = true;
